# Generated by Django 3.2.23 on 2025-12-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('furniture', 'Furniture'), ('books', 'Books'), ('supplies', 'Supplies'), ('other', 'Other')], max_length=20)),
                ('quantity', models.CharField(help_text="e.g., '5kg', '2 bags'", max_length=100)),
                ('urgency', models.CharField(choices=[('red', '🔴 Immediate (Hours)'), ('yellow', '🟡 Soon (1-2 Days)'), ('green', '🟢 Flexible')], default='green', max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('pickup_window', models.CharField(help_text="e.g., 'Today 3PM-6PM'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
