# Generated by Django 3.2.23 on 2025-12-31 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='claimed_by',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='quantity',
        ),
        migrations.AddField(
            model_name='resource',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of items available'),
        ),
        migrations.AddField(
            model_name='resource',
            name='unit',
            field=models.CharField(default='items', help_text='e.g., kg, liters, packets, pieces', max_length=50),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='resources.resource')),
            ],
        ),
    ]
