# Generated by Django 3.2.23 on 2026-01-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20251231_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('offer', 'Offer (Giving away)'), ('request', 'Request (Need help)')], default='offer', max_length=10),
        ),
    ]
