# Generated by Django 3.2.23 on 2026-01-01 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
