# Generated by Django 3.2.23 on 2026-01-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20260101_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup Only'), ('dropoff', 'I can deliver'), ('both', 'Flexible (Pickup or Drop-off)')], default='pickup', max_length=10),
        ),
    ]
